import type { TourDefinition } from "./TourEngine";

const click = (sel: string) => {
  (document.querySelector(sel) as HTMLElement | null)?.click();
};

const openRightPanel = () => {
  if (!document.querySelector('[data-tour="right-panel"]')) click('[data-tour="panel-toggle"]');
};

const openLeftNav = () => {
  if (!document.querySelector('[data-tour="main-nav"]')) click('[data-tour="menu-toggle"]');
};

/** Tour 1 — Healthcare Accessibility & Emergency Response */
export const accessibilityTour: TourDefinition = {
  id: "accessibility",
  name: "Healthcare Accessibility",
  welcome: {
    title: "Healthcare Accessibility & Emergency Response",
    intro:
      "A guided walkthrough of every control in the accessibility dashboard — from choosing a study area to routing an ambulance and exporting your analysis.",
    points: [
      "Built for health planners, NGOs, emergency responders and OSM contributors.",
      "Solves the question: where is healthcare available, and who is left uncovered?",
      "All data is live OpenStreetMap, clipped to the State or LGA you select.",
      "Use the arrow keys to move through the tour; Esc closes it at any time.",
    ],
  },
  finish: {
    title: "You're ready to explore",
    intro:
      "You now know how every panel, filter, chart and map control in the accessibility dashboard works.",
    points: [
      "Pick a State and LGA to load and clip OpenStreetMap data.",
      "Search, filter and toggle layers to isolate the facilities that matter.",
      "Locate yourself, find the nearest facilities and route to them.",
      "Read the KPIs and charts, then export CSV or GeoJSON for reporting.",
    ],
  },
  steps: [
    {
      id: "welcome-header",
      title: "Dashboard header",
      target: '[data-tour="dashboard"]',
      placement: "bottom",
      what: "The application header showing the product name, the live data indicator and the current analysis mode.",
      does: "Confirms that OpenStreetMap data is streaming live and tells you which module you are working in.",
      why: "It is your orientation bar — you always know what the map is currently showing.",
      when: "Glance at it whenever you switch modules or wonder whether data is live.",
    },
    {
      id: "logo",
      title: "Application logo & title",
      target: '[data-tour="app-logo"]',
      placement: "right",
      before: openLeftNav,
      what: "The opadbisrescue identity block at the top of the sidebar.",
      does: "Marks the workspace and acts as the home anchor of the GIS dashboard.",
      why: "Keeps the two modules — Accessibility and Data Quality — visually distinct.",
      when: "Use it as a landmark when returning from the Data Quality module.",
    },
    {
      id: "state",
      title: "State selector",
      target: '[data-tour="state-select"]',
      placement: "right",
      before: openLeftNav,
      what: "A searchable dropdown listing all 36 Nigerian states plus the FCT.",
      does: "Selecting a state loads its administrative boundary and populates the LGA list beneath it.",
      why: "Every query, statistic and chart is clipped to your study area, so nothing irrelevant is downloaded.",
      when: "Start here at the beginning of any analysis session.",
    },
    {
      id: "lga",
      title: "Local Government Area selector",
      target: '[data-tour="lga-select"]',
      placement: "right",
      before: openLeftNav,
      what: "The second dropdown, automatically filtered to the LGAs of the selected state.",
      does: "Loads the LGA boundary, zooms the map to it and refetches every OpenStreetMap layer clipped to that polygon.",
      why: "LGA-level analysis is the planning unit used by Nigerian health authorities.",
      when: "Choose an LGA whenever you need precise, locality-level accessibility numbers.",
    },
    {
      id: "nav",
      title: "Navigation menu",
      target: '[data-tour="main-nav"]',
      placement: "right",
      before: openLeftNav,
      what: "Module switcher for Dashboard, Healthcare, Accessibility, Emergency and Statistics views.",
      does: "Changes which analysis panels and map behaviours are active — for example, Emergency mode enables click-to-locate incidents.",
      why: "Keeps the interface focused on one workflow at a time instead of showing everything at once.",
      when: "Switch modes as your task changes from browsing to emergency planning or reporting.",
    },
    {
      id: "settings",
      title: "Settings & appearance",
      target: '[data-tour="settings"]',
      placement: "right",
      before: openLeftNav,
      what: "Settings mode plus the light/dark theme switch at the foot of the sidebar.",
      does: "Controls display preferences for long analysis sessions and field use.",
      why: "Dark mode reduces glare at night; satellite basemaps read better on a dark shell.",
      when: "Adjust once at the start of a session, or when working outdoors.",
    },
    {
      id: "help",
      title: "Help menu",
      target: '[data-tour="help"]',
      placement: "bottom",
      what: "The Help entry point containing both guided tours, the user manual, FAQ and keyboard shortcuts.",
      does: "Lets you relaunch this tour, or the OSM Data Quality tour, at any moment.",
      why: "Onboarding should always be one click away, not a one-off event.",
      when: "Open it whenever a control is unfamiliar or you onboard a colleague.",
    },
    {
      id: "quality-link",
      title: "OSM Data Quality module",
      target: '[data-tour="quality-link"]',
      placement: "bottom",
      what: "A shortcut to the second module of the application.",
      does: "Opens the OSM Data Quality dashboard, which audits the same facilities for missing tags, duplicates and connectivity problems.",
      why: "Accessibility conclusions are only as good as the underlying map data.",
      when: "Jump across when your accessibility results look wrong or suspiciously sparse.",
    },
    {
      id: "kpi",
      title: "Healthcare statistics bar",
      target: '[data-tour="kpi"]',
      placement: "bottom",
      what: "Live counters for hospitals, clinics, pharmacies, health centres, settlements, major roads and ambulance stations.",
      does: "Recomputes instantly from the OSM features currently loaded inside your study area.",
      why: "It is the fastest possible read on healthcare supply and emergency infrastructure coverage.",
      when: "Compare KPI values across LGAs to spot underserved localities.",
    },
    {
      id: "map",
      title: "Interactive map",
      target: '[data-tour="map"]',
      placement: "left",
      what: "The Leaflet map canvas rendering facilities, roads, settlements and your study-area boundary.",
      does: "Drag to pan, scroll or use the buttons to zoom, hover for coordinates, click a marker for a popup, and click the map in Emergency mode to drop an incident point.",
      why: "Spatial patterns — clusters, gaps, road access — only become visible on a map.",
      when: "Throughout the whole workflow; all analysis is scoped to the selected LGA shown here.",
    },
    {
      id: "basemap",
      title: "Basemap selector",
      target: '[data-tour="basemap-select"]',
      placement: "left",
      before: openRightPanel,
      what: "Switches the background imagery: OpenStreetMap, Humanitarian, Satellite, Carto Light and Carto Dark.",
      does: "OSM standard shows general context; Humanitarian emphasises clinics and tracks; Satellite reveals buildings absent from OSM; Carto Light and Dark are neutral canvases for presentations.",
      why: "The right backdrop makes thematic markers readable instead of lost in clutter.",
      when: "Use Satellite for verification, Humanitarian for field mapping, Carto for reports.",
    },
    {
      id: "layers",
      title: "Layer control",
      target: '[data-tour="layers"]',
      placement: "left",
      before: openRightPanel,
      what: "Toggles for hospitals, clinics, pharmacies, health centres, doctors, emergency stations, settlements, transport, roads and the administrative boundary.",
      does: "Turning a layer on triggers its Overpass query and draws it; turning it off removes it from the map and from the visible counts.",
      why: "Fewer layers means a clearer map and faster queries — and layer choice shapes which analyses run.",
      when: "Enable roads before connectivity work, settlements before coverage work, boundary always.",
    },
    {
      id: "locate",
      title: "Locate me",
      target: '[data-tour="locate"]',
      placement: "right",
      what: "GPS location control, fullscreen toggle, compact basemap gallery and the study-area badge.",
      does: "Detects your current position and finds the nearest hospital, clinic, pharmacy and ambulance station around you.",
      why: "In an emergency the only question that matters is what is closest right now.",
      when: "Use it in the field, or before generating a route from your own position.",
      action: {
        label: "Try Locate me",
        run: () => window.dispatchEvent(new CustomEvent("opadbisrescue:locate-me")),
      },
    },
    {
      id: "nearest",
      title: "Nearest facilities & emergency navigation",
      target: '[data-tour="nearest-panel"]',
      placement: "left",
      what: "The panel listing the closest facility of each category once your location or an incident point is known.",
      does: "Each card shows distance and estimated travel time, and Navigate draws the fastest driving or walking route with distance, duration and ETA.",
      why: "Turns a map of dots into an actionable response plan.",
      when: "During emergency simulation, dispatch planning or real field response.",
    },
    {
      id: "search",
      title: "Search bar",
      target: '[data-tour="search"]',
      placement: "left",
      before: openRightPanel,
      what: "Free-text search across loaded features.",
      does: "Filters hospitals, clinics, pharmacies, ambulance stations, towns and villages by name, in the map table and lists.",
      why: "Faster than hunting visually for a named facility.",
      when: "When you already know the facility or settlement you are looking for.",
    },
    {
      id: "filter",
      title: "Facility filter",
      target: '[data-tour="filter"]',
      placement: "left",
      before: openRightPanel,
      what: "A category filter for hospitals, clinics, pharmacies, health centres and doctors.",
      does: "Restricts the map, table and statistics to a single facility class.",
      why: "Comparing like with like is essential when measuring coverage gaps.",
      when: "Use it when studying one tier of the health system at a time.",
    },
    {
      id: "facility-table",
      title: "Facility table",
      target: '[data-tour="facility-table"]',
      placement: "top",
      what: "A sortable table of every loaded facility with name, type, operator, phone and coordinates.",
      does: "Clicking a row selects that facility and reveals its full attribute card.",
      why: "Tabular review catches missing attributes that are invisible on the map.",
      when: "Use it for systematic review, quality checks and export preparation.",
    },
    {
      id: "facility-popup",
      title: "Facility details",
      target: '[data-tour="selected-feature"]',
      placement: "left",
      before: async () => {
        openRightPanel();
        click('[data-tour="facility-table"] tbody tr');
      },
      what: "The attribute card for the selected facility, opened automatically for you.",
      does: "Shows the facility name, type badge, operator, phone, address, opening hours, accessibility tags and any other OSM tags — and is the launch point for navigation.",
      why: "These attributes decide whether a facility can actually be reached and used by a patient.",
      when: "Inspect it before recommending a facility or reporting a data gap.",
    },
    {
      id: "analytics",
      title: "Healthcare mix chart",
      target: '[data-tour="analytics"]',
      placement: "left",
      before: openRightPanel,
      what: "A donut chart of the facility composition inside the study area.",
      does: "Measures the balance between hospitals, clinics, pharmacies, health centres and doctors.",
      why: "A locality with only pharmacies has very different needs from one with a referral hospital.",
      when: "Use it when profiling an LGA or comparing two study areas.",
    },
    {
      id: "emergency-chart",
      title: "Emergency infrastructure chart",
      target: '[data-tour="emergency-chart"]',
      placement: "left",
      before: openRightPanel,
      what: "A bar chart of emergency assets such as ambulance stations and emergency-capable facilities.",
      does: "Quantifies emergency response capacity relative to the population served.",
      why: "Ambulance scarcity is the most common cause of long pre-hospital delays.",
      when: "Use it when planning emergency coverage or justifying investment.",
    },
    {
      id: "accessibility-analysis",
      title: "Accessibility analysis",
      target: '[data-tour="kpi"]',
      placement: "bottom",
      what: "The combined reading of facility counts, road network and settlement layers.",
      does: "Supports travel-time reasoning, coverage estimation, underserved-area detection and healthcare-desert identification — settlements far from any facility along the road network.",
      why: "Coverage gaps, not facility totals, determine real health outcomes.",
      when: "Run it per LGA when prioritising where the next clinic should be built.",
    },
    {
      id: "export",
      title: "Export tools",
      target: '[data-tour="export"]',
      placement: "left",
      before: openRightPanel,
      what: "Download buttons for the currently filtered facilities.",
      does: "CSV for spreadsheets and statistics, GeoJSON for QGIS/ArcGIS; the map view can be captured for PDF and report use.",
      why: "Analysis must leave the browser to become a decision document.",
      when: "Export at the end of a study, or to share evidence with partners.",
    },
  ],
};
