import type { TourDefinition } from "./TourEngine";

const click = (sel: string) => {
  (document.querySelector(sel) as HTMLElement | null)?.click();
};

const openTab = (value: string) => click(`[data-tour="q-tabs"] [data-value="${value}"]`);

/** Tour 2 — OSM Data Quality Dashboard */
export const qualityTour: TourDefinition = {
  id: "quality",
  name: "OSM Data Quality",
  welcome: {
    title: "OSM Data Quality Dashboard",
    intro:
      "A guided walkthrough of the auditing module: how facility data is scored, how issues are detected, and how you fix them in OpenStreetMap.",
    points: [
      "Built for OSM contributors, GIS analysts, NGOs and health data teams.",
      "Answers: can I trust this data, and what exactly needs fixing?",
      "Every metric is computed live for the State or LGA you select.",
      "Arrow keys navigate the tour; Esc closes it at any time.",
    ],
  },
  finish: {
    title: "You can now audit any LGA",
    intro: "You have seen every scorecard, filter, explorer tab and export in the quality module.",
    points: [
      "Score an area, then read the KPI cards and quality bands.",
      "Filter to a single issue type and work through the error explorer.",
      "Resolve duplicates and road-connectivity gaps directly in OSM.",
      "Export CSV, GeoJSON or an HTML report to share your audit.",
    ],
  },
  steps: [
    {
      id: "q-header",
      title: "Quality dashboard header",
      target: '[data-tour="q-header"]',
      placement: "bottom",
      what: "The header of the OSM Data Quality module, with the live data indicator and module actions.",
      does: "Confirms which module you are in and that scoring is running on freshly fetched OpenStreetMap data.",
      why: "Quality results are only meaningful when you know they reflect the current map.",
      when: "Check it whenever you return to the module or change study area.",
    },
    {
      id: "q-nav",
      title: "Back to Accessibility",
      target: '[data-tour="q-nav"]',
      placement: "bottom",
      what: "The link back to the Healthcare Accessibility module.",
      does: "Returns you to the accessibility dashboard while keeping the same State and LGA selection.",
      why: "Auditing and analysis are two halves of the same workflow.",
      when: "Switch back once you have verified that the data is trustworthy.",
    },
    {
      id: "q-area",
      title: "Study area selector",
      target: '[data-tour="area-selector"]',
      placement: "right",
      what: "The same cascading State → LGA selector used across the application.",
      does: "Clips all quality scoring, issue detection and duplicate analysis to the chosen administrative boundary.",
      why: "Data quality varies enormously between LGAs; national averages hide the problems.",
      when: "Set it first — every number on this page depends on it.",
    },
    {
      id: "q-kpi",
      title: "Quality scorecards",
      target: '[data-tour="q-kpi"]',
      placement: "bottom",
      what: "Headline cards for the overall data-quality score, complete versus incomplete facilities, duplicate candidates and connectivity gaps.",
      does: "Aggregates the per-facility scores computed from name, type, operator, contact, address, opening hours and location tags.",
      why: "One glance tells you whether the area is map-ready or needs a mapping campaign.",
      when: "Read it first, before diving into individual issues.",
    },
    {
      id: "q-bands",
      title: "Quality bands & scoring",
      target: '[data-tour="q-kpi"]',
      placement: "bottom",
      what: "The Excellent / Good / Fair / Poor bands behind the score.",
      does: "Each facility earns points for completeness (required tags present), accuracy (plausible values), consistency (tag combinations) and location precision; the weighted total maps to a band.",
      why: "Bands turn an abstract percentage into a clear action threshold.",
      when: "Use bands to triage: fix Poor first, then Fair.",
    },
    {
      id: "q-filters",
      title: "Filters",
      target: '[data-tour="q-filters"]',
      placement: "bottom",
      what: "Search plus facility-type, quality-band and issue-type filters.",
      does: "Narrows the map, the explorer tabs and the exports to exactly the subset you want to fix.",
      why: "Fixing one issue class at a time — for example all unnamed clinics — is far faster than ad-hoc editing.",
      when: "Use before every editing session to build your work queue.",
    },
    {
      id: "q-map",
      title: "Quality map",
      target: '[data-tour="q-map"]',
      placement: "left",
      what: "The map canvas with facilities coloured by quality band and clustered by average score.",
      does: "Click any marker to inspect its tags, its detected issues and direct links to edit it in OSM.",
      why: "Quality problems are geographic — whole neighbourhoods are often mapped by one contributor with one habit.",
      when: "Use it to spot spatial clusters of poor data before editing.",
    },
    {
      id: "q-mapctl",
      title: "Map controls",
      target: '[data-tour="q-mapctl"]',
      placement: "left",
      what: "Basemap switcher (including satellite imagery), locate, fullscreen and boundary controls.",
      does: "Satellite imagery lets you verify whether a facility really exists at the mapped location.",
      why: "Verification against imagery is the core of responsible OSM editing.",
      when: "Switch to satellite whenever you suspect a misplaced or invented feature.",
    },
    {
      id: "q-locate",
      title: "Locate me & nearby quality",
      target: '[data-tour="q-locate"]',
      placement: "left",
      what: "GPS location, synchronised with the accessibility module.",
      does: "Centres the map on your position and scores the facilities immediately around you.",
      why: "Ground-truthing nearby facilities is the highest-value contribution a local mapper can make.",
      when: "Use it during field surveys and mapathons.",
    },
    {
      id: "q-tab-issues",
      title: "Error explorer",
      target: '[data-tour="q-tabs"]',
      placement: "top",
      before: () => openTab("issues"),
      what: "A ranked list of every detected data problem with severity and the affected facility.",
      does: "Groups issues such as missing names, missing types, missing contact details, missing opening hours and implausible values.",
      why: "It is your prioritised to-do list for improving the map.",
      when: "Work through it top-down after filtering to an area or issue type.",
    },
    {
      id: "q-tab-duplicates",
      title: "Duplicate detection",
      target: '[data-tour="q-tabs"]',
      placement: "top",
      before: () => openTab("duplicates"),
      what: "Candidate pairs of facilities that appear to be the same real-world place mapped twice.",
      does: "Compares proximity and name similarity to surface likely duplicates for human review.",
      why: "Duplicates inflate facility counts and distort every accessibility statistic.",
      when: "Review before publishing any facility count for an LGA.",
    },
    {
      id: "q-tab-connectivity",
      title: "Road connectivity",
      target: '[data-tour="q-tabs"]',
      placement: "top",
      before: () => openTab("connectivity"),
      what: "Facilities that are not reachable from the mapped road network, plus disconnected road segments.",
      does: "Flags missing access ways and orphaned roads that break routing.",
      why: "A facility that cannot be routed to is invisible to an ambulance dispatcher.",
      when: "Fix these before running any travel-time or emergency-response analysis.",
    },
    {
      id: "q-tab-charts",
      title: "Analytics & charts",
      target: '[data-tour="q-tabs"]',
      placement: "top",
      before: () => openTab("charts"),
      what: "Distribution charts for quality bands, completeness by tag and issues by facility type.",
      does: "Shows which attributes are systematically missing across the study area.",
      why: "Systematic gaps are best solved with a targeted mapping campaign, not one-by-one edits.",
      when: "Use when planning a mapathon or reporting progress over time.",
    },
    {
      id: "q-tab-guidance",
      title: "Contribution guidance",
      target: '[data-tour="q-tabs"]',
      placement: "top",
      before: () => openTab("guidance"),
      what: "Practical instructions for improving the data in OpenStreetMap.",
      does: "Explains the recommended tags for health facilities and links each flagged feature to the OSM iD editor.",
      why: "Fixes made upstream in OSM benefit every user of the data, not just this dashboard.",
      when: "Open it when you are ready to edit, or when onboarding new contributors.",
    },
    {
      id: "q-export",
      title: "Export & reporting",
      target: '[data-tour="q-export"]',
      placement: "bottom",
      what: "Download options for the scored facilities and detected issues.",
      does: "Produces CSV, GeoJSON, JSON or a shareable HTML quality report of the current filtered selection.",
      why: "Audit results need to be shared with mapping teams and health authorities.",
      when: "Export at the end of an audit, or to track quality improvements over time.",
    },
    {
      id: "q-help",
      title: "Help & tour",
      target: '[data-tour="q-help"]',
      placement: "bottom",
      what: "The help entry point for this module.",
      does: "Relaunches this tour whenever you or a colleague needs a refresher.",
      why: "Quality auditing has many concepts — revisit them on demand.",
      when: "Any time; the tour never blocks your work.",
    },
  ],
};
